services:
  n8n:
    image: n8nio/n8n
    ports:
  - "127.0.0.1:5678:5678"

    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
    volumes:
      - ./n8n-data:/home/node/.n8n

