services:
  prometheus:
    image: prom/prometheus
    container_name: forge-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter
    container_name: forge-node-exporter
    # Commented out to avoid port conflict with systemd version
    # ports:
    #   - "9100:9100"
    restart: unless-stopped

